using System.Collections.Generic;

namespace BlaineRP.Client.Game.Management.Animations
{
    public partial class Core
    {
        public static Dictionary<WalkstyleType, string> WalkstylesList { get; private set; } = new Dictionary<WalkstyleType, string>()
        {
            { WalkstyleType.Alien, "move_m@alien" },
            { WalkstyleType.Armored, "anim_group_move_ballistic" },
            { WalkstyleType.Arrogant, "move_f@arrogant@a" },
            { WalkstyleType.Brave, "move_m@brave" },
            { WalkstyleType.Casual, "move_m@casual@a" },
            { WalkstyleType.Casual2, "move_m@casual@b" },
            { WalkstyleType.Casual3, "move_m@casual@c" },
            { WalkstyleType.Casual4, "move_m@casual@d" },
            { WalkstyleType.Casual5, "move_m@casual@e" },
            { WalkstyleType.Casual6, "move_m@casual@f" },
            { WalkstyleType.Chichi, "move_f@chichi" },
            { WalkstyleType.Confident, "move_m@confident" },
            { WalkstyleType.Cop, "move_m@business@a" },
            { WalkstyleType.Cop2, "move_m@business@b" },
            { WalkstyleType.Cop3, "move_m@business@c" },
            { WalkstyleType.DefaultMale, "move_m@multiplayer" },
            { WalkstyleType.DefaultFemale, "move_f@multiplayer" },
            { WalkstyleType.Drunk, "move_m@drunk@a" },
            { WalkstyleType.Drunk2, "move_m@drunk@slightlydrunk" },
            { WalkstyleType.Drunk3, "move_m@buzzed" },
            { WalkstyleType.Drunk4, "move_m@drunk@verydrunk" },
            { WalkstyleType.Femme, "move_f@femme@" },
            { WalkstyleType.Fire, "move_characters@franklin@fire" },
            { WalkstyleType.Fire2, "move_characters@michael@fire" },
            { WalkstyleType.Fire3, "move_m@fire" },
            { WalkstyleType.Flee, "move_f@flee@a" },
            { WalkstyleType.Franklin, "move_p_m_one" },
            { WalkstyleType.Gangster, "move_m@gangster@generic" },
            { WalkstyleType.Gangster2, "move_m@gangster@ng" },
            { WalkstyleType.Gangster3, "move_m@gangster@var_e" },
            { WalkstyleType.Gangster4, "move_m@gangster@var_f" },
            { WalkstyleType.Gangster5, "move_m@gangster@var_i" },
            { WalkstyleType.Grooving, "anim@move_m@grooving@" },
            { WalkstyleType.Guard, "move_m@prison_gaurd" },
            { WalkstyleType.Handcuffs, "move_m@prisoner_cuffed" },
            { WalkstyleType.Heels, "move_f@heels@c" },
            { WalkstyleType.Heels2, "move_f@heels@d" },
            { WalkstyleType.Hiking, "move_m@hiking" },
            { WalkstyleType.Hipster, "move_m@hipster@a" },
            { WalkstyleType.Hobo, "move_m@hobo@a" },
            { WalkstyleType.Hurry, "move_f@hurry@a" },
            { WalkstyleType.Janitor, "move_p_m_zero_janitor" },
            { WalkstyleType.Janitor2, "move_p_m_zero_slow" },
            { WalkstyleType.Jog, "move_m@jog@" },
            { WalkstyleType.Lemar, "anim_group_move_lemar_alley" },
            { WalkstyleType.Lester, "move_heist_lester" },
            { WalkstyleType.Lester2, "move_lester_caneup" },
            { WalkstyleType.Maneater, "move_f@maneater" },
            { WalkstyleType.Michael, "move_ped_bucket" },
            { WalkstyleType.Money, "move_m@money" },
            { WalkstyleType.Muscle, "move_m@muscle@a" },
            { WalkstyleType.Posh, "move_m@posh@" },
            { WalkstyleType.Posh2, "move_f@posh@" },
            { WalkstyleType.Quick, "move_m@quick" },
            { WalkstyleType.Runner, "female_fast_runner" },
            { WalkstyleType.Sad, "move_m@sad@a" },
            { WalkstyleType.Sassy, "move_m@sassy" },
            { WalkstyleType.Sassy2, "move_f@sassy" },
            { WalkstyleType.Scared, "move_f@scared" },
            { WalkstyleType.Sexy, "move_f@sexy@a" },
            { WalkstyleType.Shady, "move_m@shadyped@a" },
            { WalkstyleType.Slow, "move_characters@jimmy@slow@" },
            { WalkstyleType.Swagger, "move_m@swagger" },
            { WalkstyleType.Tough, "move_m@tough_guy@" },
            { WalkstyleType.Tough2, "move_f@tough_guy@" },
            { WalkstyleType.Trash, "clipset@move@trash_fast_turn" },
            { WalkstyleType.Trash2, "missfbi4prepp1_garbageman" },
            { WalkstyleType.Trevor, "move_p_m_two" },
            { WalkstyleType.Wide, "move_m@bag" },
        };
    }
}