using System.Collections.Generic;
using BlaineRP.Client.Animations.Enums;

namespace BlaineRP.Client.Animations
{
    public partial class Script
    {
        public static Dictionary<WalkstyleTypes, string> WalkstylesList { get; private set; } =
            new Dictionary<WalkstyleTypes, string>()
            {
                { WalkstyleTypes.Alien, "move_m@alien" },
                { WalkstyleTypes.Armored, "anim_group_move_ballistic" },
                { WalkstyleTypes.Arrogant, "move_f@arrogant@a" },
                { WalkstyleTypes.Brave, "move_m@brave" },
                { WalkstyleTypes.Casual, "move_m@casual@a" },
                { WalkstyleTypes.Casual2, "move_m@casual@b" },
                { WalkstyleTypes.Casual3, "move_m@casual@c" },
                { WalkstyleTypes.Casual4, "move_m@casual@d" },
                { WalkstyleTypes.Casual5, "move_m@casual@e" },
                { WalkstyleTypes.Casual6, "move_m@casual@f" },
                { WalkstyleTypes.Chichi, "move_f@chichi" },
                { WalkstyleTypes.Confident, "move_m@confident" },
                { WalkstyleTypes.Cop, "move_m@business@a" },
                { WalkstyleTypes.Cop2, "move_m@business@b" },
                { WalkstyleTypes.Cop3, "move_m@business@c" },
                { WalkstyleTypes.DefaultMale, "move_m@multiplayer" },
                { WalkstyleTypes.DefaultFemale, "move_f@multiplayer" },
                { WalkstyleTypes.Drunk, "move_m@drunk@a" },
                { WalkstyleTypes.Drunk2, "move_m@drunk@slightlydrunk" },
                { WalkstyleTypes.Drunk3, "move_m@buzzed" },
                { WalkstyleTypes.Drunk4, "move_m@drunk@verydrunk" },
                { WalkstyleTypes.Femme, "move_f@femme@" },
                { WalkstyleTypes.Fire, "move_characters@franklin@fire" },
                { WalkstyleTypes.Fire2, "move_characters@michael@fire" },
                { WalkstyleTypes.Fire3, "move_m@fire" },
                { WalkstyleTypes.Flee, "move_f@flee@a" },
                { WalkstyleTypes.Franklin, "move_p_m_one" },
                { WalkstyleTypes.Gangster, "move_m@gangster@generic" },
                { WalkstyleTypes.Gangster2, "move_m@gangster@ng" },
                { WalkstyleTypes.Gangster3, "move_m@gangster@var_e" },
                { WalkstyleTypes.Gangster4, "move_m@gangster@var_f" },
                { WalkstyleTypes.Gangster5, "move_m@gangster@var_i" },
                { WalkstyleTypes.Grooving, "anim@move_m@grooving@" },
                { WalkstyleTypes.Guard, "move_m@prison_gaurd" },
                { WalkstyleTypes.Handcuffs, "move_m@prisoner_cuffed" },
                { WalkstyleTypes.Heels, "move_f@heels@c" },
                { WalkstyleTypes.Heels2, "move_f@heels@d" },
                { WalkstyleTypes.Hiking, "move_m@hiking" },
                { WalkstyleTypes.Hipster, "move_m@hipster@a" },
                { WalkstyleTypes.Hobo, "move_m@hobo@a" },
                { WalkstyleTypes.Hurry, "move_f@hurry@a" },
                { WalkstyleTypes.Janitor, "move_p_m_zero_janitor" },
                { WalkstyleTypes.Janitor2, "move_p_m_zero_slow" },
                { WalkstyleTypes.Jog, "move_m@jog@" },
                { WalkstyleTypes.Lemar, "anim_group_move_lemar_alley" },
                { WalkstyleTypes.Lester, "move_heist_lester" },
                { WalkstyleTypes.Lester2, "move_lester_caneup" },
                { WalkstyleTypes.Maneater, "move_f@maneater" },
                { WalkstyleTypes.Michael, "move_ped_bucket" },
                { WalkstyleTypes.Money, "move_m@money" },
                { WalkstyleTypes.Muscle, "move_m@muscle@a" },
                { WalkstyleTypes.Posh, "move_m@posh@" },
                { WalkstyleTypes.Posh2, "move_f@posh@" },
                { WalkstyleTypes.Quick, "move_m@quick" },
                { WalkstyleTypes.Runner, "female_fast_runner" },
                { WalkstyleTypes.Sad, "move_m@sad@a" },
                { WalkstyleTypes.Sassy, "move_m@sassy" },
                { WalkstyleTypes.Sassy2, "move_f@sassy" },
                { WalkstyleTypes.Scared, "move_f@scared" },
                { WalkstyleTypes.Sexy, "move_f@sexy@a" },
                { WalkstyleTypes.Shady, "move_m@shadyped@a" },
                { WalkstyleTypes.Slow, "move_characters@jimmy@slow@" },
                { WalkstyleTypes.Swagger, "move_m@swagger" },
                { WalkstyleTypes.Tough, "move_m@tough_guy@" },
                { WalkstyleTypes.Tough2, "move_f@tough_guy@" },
                { WalkstyleTypes.Trash, "clipset@move@trash_fast_turn" },
                { WalkstyleTypes.Trash2, "missfbi4prepp1_garbageman" },
                { WalkstyleTypes.Trevor, "move_p_m_two" },
                { WalkstyleTypes.Wide, "move_m@bag" },
            };
    }
}