//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCRPServer.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BCRPServer.Properties.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [BAC] Игрок {0} подозревается в телепорте! Дистанция: {1}.
        /// </summary>
        public static string CHAT_ADMIN_AC_TP_0 {
            get {
                return ResourceManager.GetString("CHAT_ADMIN_AC_TP_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [SKick] {0} выгнал игрока {1} с сервера. Причина: {2}.
        /// </summary>
        public static string CHAT_ADMIN_KICK_SILENT_0 {
            get {
                return ResourceManager.GetString("CHAT_ADMIN_KICK_SILENT_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на передал(а) лекарство {0}.
        /// </summary>
        public static string CHAT_EMS_PHEAL_0 {
            get {
                return ResourceManager.GetString("CHAT_EMS_PHEAL_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на принял(а) и употребил(а) лекарство от {0}.
        /// </summary>
        public static string CHAT_EMS_PHEAL_1 {
            get {
                return ResourceManager.GetString("CHAT_EMS_PHEAL_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на снял(а) наручники с рук {0}.
        /// </summary>
        public static string CHAT_PLAYER_CUFFS_OFF_0 {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_CUFFS_OFF_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на срезал(а) стяжки с рук {0}.
        /// </summary>
        public static string CHAT_PLAYER_CUFFS_OFF_1 {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_CUFFS_OFF_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на надел(а) наручники на руки {0}.
        /// </summary>
        public static string CHAT_PLAYER_CUFFS_ON_0 {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_CUFFS_ON_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на связал(а) стяжками руки {0}.
        /// </summary>
        public static string CHAT_PLAYER_CUFFS_ON_1 {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_CUFFS_ON_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ослабил(а) хватку и отпустил(а) {0}.
        /// </summary>
        public static string CHAT_PLAYER_ESCORT_OFF {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_ESCORT_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на заломал(а) {0} и повел(а) за собой.
        /// </summary>
        public static string CHAT_PLAYER_ESCORT_ON {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_ESCORT_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на показал(а) пальцем на {0}.
        /// </summary>
        public static string CHAT_PLAYER_FP_0 {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_FP_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на показал(а) пальцем на человека.
        /// </summary>
        public static string CHAT_PLAYER_FP_1 {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_FP_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на подбросил(а) монетку.
        /// </summary>
        public static string CHAT_PLAYER_HEADSORTAILS_0 {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_HEADSORTAILS_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На подброшенной монетке выпал орёл..
        /// </summary>
        public static string CHAT_PLAYER_HEADSORTAILS_1 {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_HEADSORTAILS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На подброшенной монетке выпала решка..
        /// </summary>
        public static string CHAT_PLAYER_HEADSORTAILS_2 {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_HEADSORTAILS_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на сорвал(а) маску с {0}.
        /// </summary>
        public static string CHAT_PLAYER_MASKOFF_0 {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_MASKOFF_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на вытащил(а) {0} из {1}.
        /// </summary>
        public static string CHAT_PLAYER_OUTOFVEH_0 {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_OUTOFVEH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на вытащил(а) {0} из багажника {1}.
        /// </summary>
        public static string CHAT_PLAYER_OUTOFVEH_1 {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_OUTOFVEH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на убрал(а) телефон.
        /// </summary>
        public static string CHAT_PLAYER_PHONE_OFF {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_PHONE_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на достал(а) телефон.
        /// </summary>
        public static string CHAT_PLAYER_PHONE_ON {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_PHONE_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сведения о человеке найдены в служебном планшете..
        /// </summary>
        public static string CHAT_PLAYER_POLICE_TABLETPC_FOUND {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_POLICE_TABLETPC_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на убрал(а) служебный планшет.
        /// </summary>
        public static string CHAT_PLAYER_POLICE_TABLETPC_OFF {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_POLICE_TABLETPC_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на достал(а) служебный планшет.
        /// </summary>
        public static string CHAT_PLAYER_POLICE_TABLETPC_ON {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_POLICE_TABLETPC_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При обыске обнаружен {0}..
        /// </summary>
        public static string CHAT_PLAYER_PSEARCH_CONFISCATE_0 {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_PSEARCH_CONFISCATE_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на конфисковал(а) предмет у {0}.
        /// </summary>
        public static string CHAT_PLAYER_PSEARCH_CONFISCATE_1 {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_PSEARCH_CONFISCATE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При обыске {0} обнаружено {1} документов..
        /// </summary>
        public static string CHAT_PLAYER_PSEARCH_DOCS_FOUND {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_PSEARCH_DOCS_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на взял(а) в руки и просмотрел(а) паспорт {0}.
        /// </summary>
        public static string CHAT_PLAYER_PSEARCH_DOCS_LOOK_0 {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_PSEARCH_DOCS_LOOK_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на взял(а) в руки и просмотрел(а) лицензии {0}.
        /// </summary>
        public static string CHAT_PLAYER_PSEARCH_DOCS_LOOK_1 {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_PSEARCH_DOCS_LOOK_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на взял(а) в руки и просмотрел(а) мед. карту {0}.
        /// </summary>
        public static string CHAT_PLAYER_PSEARCH_DOCS_LOOK_2 {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_PSEARCH_DOCS_LOOK_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на взял(а) в руки и просмотрел(а) трудовую книжку {0}.
        /// </summary>
        public static string CHAT_PLAYER_PSEARCH_DOCS_LOOK_3 {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_PSEARCH_DOCS_LOOK_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на взял(а) в руки и просмотрел(а) удостоверение {0}.
        /// </summary>
        public static string CHAT_PLAYER_PSEARCH_DOCS_LOOK_4 {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_PSEARCH_DOCS_LOOK_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При обыске {0} в карманах обнаружено {1} потенциально нелегальных предметов..
        /// </summary>
        public static string CHAT_PLAYER_PSEARCH_ITEMS_0_FOUND {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_PSEARCH_ITEMS_0_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При обыске {0} в сумке обнаружено {1} потенциально нелегальных предметов..
        /// </summary>
        public static string CHAT_PLAYER_PSEARCH_ITEMS_1_FOUND {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_PSEARCH_ITEMS_1_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При обыске {0} обнаружено {1} потенциально нелегальных предметов..
        /// </summary>
        public static string CHAT_PLAYER_PSEARCH_ITEMS_2_FOUND {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_PSEARCH_ITEMS_2_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При обыске {0} в кобуре обнаружено {1} потенциально нелегальных предметов..
        /// </summary>
        public static string CHAT_PLAYER_PSEARCH_ITEMS_3_FOUND {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_PSEARCH_ITEMS_3_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на надел(а) одноразовые перчатки и приступил(а) к обыску {0}.
        /// </summary>
        public static string CHAT_PLAYER_PSEARCH_START {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_PSEARCH_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на посадил(а) {0} в {1}.
        /// </summary>
        public static string CHAT_PLAYER_PUSHTOVEH_0 {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_PUSHTOVEH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на затолкнул(а) {0} в багажник {1}.
        /// </summary>
        public static string CHAT_PLAYER_PUSHTOVEH_1 {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_PUSHTOVEH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на начал(а) оказывать первую медицинскую помощь {0}.
        /// </summary>
        public static string CHAT_PLAYER_RESURRECT_0 {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_RESURRECT_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на оказал(а) первую медицинскую помощь {0}.
        /// </summary>
        public static string CHAT_PLAYER_RESURRECT_1 {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_RESURRECT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на подобрал(а) {0}.
        /// </summary>
        public static string CHAT_PLAYER_TAKEN {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_TAKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При обыске обнаружен {0}..
        /// </summary>
        public static string CHAT_PLAYER_VSEARCH_CONFISCATE_0 {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_VSEARCH_CONFISCATE_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на конфисковал(а) предмет из багажника {0}.
        /// </summary>
        public static string CHAT_PLAYER_VSEARCH_CONFISCATE_1 {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_VSEARCH_CONFISCATE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При обыске {0} в багажнике обнаружено {1} потенциально нелегальных предметов..
        /// </summary>
        public static string CHAT_PLAYER_VSEARCH_ITEMS_FOUND_0 {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_VSEARCH_ITEMS_FOUND_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на надел(а) одноразовые перчатки и приступил(а) к обыску {0}.
        /// </summary>
        public static string CHAT_PLAYER_VSEARCH_START {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_VSEARCH_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на достал(а) {0}.
        /// </summary>
        public static string CHAT_PLAYER_WEAPON_EQUIP_0 {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_WEAPON_EQUIP_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на достал(а) из кобуры {0}.
        /// </summary>
        public static string CHAT_PLAYER_WEAPON_EQUIP_1 {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_WEAPON_EQUIP_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на убрал(а) {0}.
        /// </summary>
        public static string CHAT_PLAYER_WEAPON_UNEQUIP_0 {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_WEAPON_UNEQUIP_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на убрал(а) в кобуру {0}.
        /// </summary>
        public static string CHAT_PLAYER_WEAPON_UNEQUIP_1 {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_WEAPON_UNEQUIP_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} уменьшил(а) срок в СИЗО на {1} мин. по делу {2).
        /// </summary>
        public static string CHAT_POLICE_ARRESTCHANGE_0 {
            get {
                return ResourceManager.GetString("CHAT_POLICE_ARRESTCHANGE_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} увеличил(а) срок в СИЗО на {1} мин. по делу {2).
        /// </summary>
        public static string CHAT_POLICE_ARRESTCHANGE_1 {
            get {
                return ResourceManager.GetString("CHAT_POLICE_ARRESTCHANGE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} закрыл(а) дело {1} и выпустил(а) из СИЗО {2} ({3}).
        /// </summary>
        public static string CHAT_POLICE_ARRESTCHANGE_2 {
            get {
                return ResourceManager.GetString("CHAT_POLICE_ARRESTCHANGE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Через {0} секунд будет произведена очистка предметов, лежащих на земле!.
        /// </summary>
        public static string CHAT_SERVER_WORLD_CLEARITEMS_0 {
            get {
                return ResourceManager.GetString("CHAT_SERVER_WORLD_CLEARITEMS_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Было удалено {0} предметов!.
        /// </summary>
        public static string CHAT_SERVER_WORLD_CLEARITEMS_1 {
            get {
                return ResourceManager.GetString("CHAT_SERVER_WORLD_CLEARITEMS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаление предметов было отменено!.
        /// </summary>
        public static string CHAT_SERVER_WORLD_CLEARITEMS_2 {
            get {
                return ResourceManager.GetString("CHAT_SERVER_WORLD_CLEARITEMS_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на отстегнул(а) ремень безопасности.
        /// </summary>
        public static string CHAT_VEHICLE_BELT_OFF {
            get {
                return ResourceManager.GetString("CHAT_VEHICLE_BELT_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на пристегнул(а) ремень безопасности.
        /// </summary>
        public static string CHAT_VEHICLE_BELT_ON {
            get {
                return ResourceManager.GetString("CHAT_VEHICLE_BELT_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на заблокировал(а) двери.
        /// </summary>
        public static string CHAT_VEHICLE_DOORS_LOCKED {
            get {
                return ResourceManager.GetString("CHAT_VEHICLE_DOORS_LOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на разблокировал(а) двери.
        /// </summary>
        public static string CHAT_VEHICLE_DOORS_UNLOCKED {
            get {
                return ResourceManager.GetString("CHAT_VEHICLE_DOORS_UNLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Двигатель заглох..
        /// </summary>
        public static string CHAT_VEHICLE_ENGINE_BROKEN_0 {
            get {
                return ResourceManager.GetString("CHAT_VEHICLE_ENGINE_BROKEN_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Двигатель не заводится..
        /// </summary>
        public static string CHAT_VEHICLE_ENGINE_BROKEN_1 {
            get {
                return ResourceManager.GetString("CHAT_VEHICLE_ENGINE_BROKEN_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на заглушил(а) двигатель.
        /// </summary>
        public static string CHAT_VEHICLE_ENGINE_OFF {
            get {
                return ResourceManager.GetString("CHAT_VEHICLE_ENGINE_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на запустил(а) двигатель.
        /// </summary>
        public static string CHAT_VEHICLE_ENGINE_ON {
            get {
                return ResourceManager.GetString("CHAT_VEHICLE_ENGINE_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Топливо закончилось..
        /// </summary>
        public static string CHAT_VEHICLE_FUEL_OUTOF {
            get {
                return ResourceManager.GetString("CHAT_VEHICLE_FUEL_OUTOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на закрыл(а) капот.
        /// </summary>
        public static string CHAT_VEHICLE_HOOD_LOCKED {
            get {
                return ResourceManager.GetString("CHAT_VEHICLE_HOOD_LOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на открыл(а) капот.
        /// </summary>
        public static string CHAT_VEHICLE_HOOD_UNLOCKED {
            get {
                return ResourceManager.GetString("CHAT_VEHICLE_HOOD_UNLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на убрал(а) шасси.
        /// </summary>
        public static string CHAT_VEHICLE_LGEAR_OFF {
            get {
                return ResourceManager.GetString("CHAT_VEHICLE_LGEAR_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на выпустил(а) шасси.
        /// </summary>
        public static string CHAT_VEHICLE_LGEAR_ON {
            get {
                return ResourceManager.GetString("CHAT_VEHICLE_LGEAR_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на выключил(а) свет фар.
        /// </summary>
        public static string CHAT_VEHICLE_LIGHTS_OFF {
            get {
                return ResourceManager.GetString("CHAT_VEHICLE_LIGHTS_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на включил(а) свет фар.
        /// </summary>
        public static string CHAT_VEHICLE_LIGHTS_ON {
            get {
                return ResourceManager.GetString("CHAT_VEHICLE_LIGHTS_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на без номерного знака.
        /// </summary>
        public static string CHAT_VEHICLE_NP_NONE {
            get {
                return ResourceManager.GetString("CHAT_VEHICLE_NP_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на вышвырнул(а) {0} из транспорта.
        /// </summary>
        public static string CHAT_VEHICLE_PSGR_KICKED {
            get {
                return ResourceManager.GetString("CHAT_VEHICLE_PSGR_KICKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на закрыл(а) багажник.
        /// </summary>
        public static string CHAT_VEHICLE_TRUNK_LOCKED {
            get {
                return ResourceManager.GetString("CHAT_VEHICLE_TRUNK_LOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на открыл(а) багажник.
        /// </summary>
        public static string CHAT_VEHICLE_TRUNK_UNLOCKED {
            get {
                return ResourceManager.GetString("CHAT_VEHICLE_TRUNK_UNLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Армия.
        /// </summary>
        public static string FRACTION_ARMY_FZ_NAME {
            get {
                return ResourceManager.GetString("FRACTION_ARMY_FZ_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Полиция Округа Блэйн.
        /// </summary>
        public static string FRACTION_COP_BLAINE_NAME {
            get {
                return ResourceManager.GetString("FRACTION_COP_BLAINE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Полиция Лос-Сантоса.
        /// </summary>
        public static string FRACTION_COP_LS_NAME {
            get {
                return ResourceManager.GetString("FRACTION_COP_LS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Больница Округа Блэйн.
        /// </summary>
        public static string FRACTION_EMS_BLAINE_NAME {
            get {
                return ResourceManager.GetString("FRACTION_EMS_BLAINE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Больница Лос-Сантоса.
        /// </summary>
        public static string FRACTION_EMS_LS_NAME {
            get {
                return ResourceManager.GetString("FRACTION_EMS_LS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на F.I.B..
        /// </summary>
        public static string FRACTION_FIB_LS_NAME {
            get {
                return ResourceManager.GetString("FRACTION_FIB_LS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The Ballas Gang.
        /// </summary>
        public static string FRACTION_GANG_BALS_NAME {
            get {
                return ResourceManager.GetString("FRACTION_GANG_BALS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The Families.
        /// </summary>
        public static string FRACTION_GANG_FAMS_NAME {
            get {
                return ResourceManager.GetString("FRACTION_GANG_FAMS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Marabunta Grande.
        /// </summary>
        public static string FRACTION_GANG_MARA_NAME {
            get {
                return ResourceManager.GetString("FRACTION_GANG_MARA_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Los Santos Vagos.
        /// </summary>
        public static string FRACTION_GANG_VAGS_NAME {
            get {
                return ResourceManager.GetString("FRACTION_GANG_VAGS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Правительство Лос-Сантоса.
        /// </summary>
        public static string FRACTION_GOV_LS_NAME {
            get {
                return ResourceManager.GetString("FRACTION_GOV_LS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на La Cosa Nostra.
        /// </summary>
        public static string FRACTION_MAFIA_ITA_NAME {
            get {
                return ResourceManager.GetString("FRACTION_MAFIA_ITA_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yakuza.
        /// </summary>
        public static string FRACTION_MAFIA_JAP_NAME {
            get {
                return ResourceManager.GetString("FRACTION_MAFIA_JAP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Русская Мафия.
        /// </summary>
        public static string FRACTION_MAFIA_RUS_NAME {
            get {
                return ResourceManager.GetString("FRACTION_MAFIA_RUS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Weazel News.
        /// </summary>
        public static string FRACTION_MEDIA_LS_NAME {
            get {
                return ResourceManager.GetString("FRACTION_MEDIA_LS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на S.A.S.P.A..
        /// </summary>
        public static string FRACTION_PRISON_BB_NAME {
            get {
                return ResourceManager.GetString("FRACTION_PRISON_BB_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Федеральная тюрьма.
        /// </summary>
        public static string FRACTION_PRISON_BB_NAME_PLACE {
            get {
                return ResourceManager.GetString("FRACTION_PRISON_BB_NAME_PLACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IP-адрес.
        /// </summary>
        public static string GEN_BAN_GLOBAL_BTYPES_0 {
            get {
                return ResourceManager.GetString("GEN_BAN_GLOBAL_BTYPES_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Серийный номер.
        /// </summary>
        public static string GEN_BAN_GLOBAL_BTYPES_1 {
            get {
                return ResourceManager.GetString("GEN_BAN_GLOBAL_BTYPES_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Social Club.
        /// </summary>
        public static string GEN_BAN_GLOBAL_BTYPES_2 {
            get {
                return ResourceManager.GetString("GEN_BAN_GLOBAL_BTYPES_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЧС проекта.
        /// </summary>
        public static string GEN_BAN_GLOBAL_BTYPES_3 {
            get {
                return ResourceManager.GetString("GEN_BAN_GLOBAL_BTYPES_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ID блокировки: {0}\nТип: {1}\nДата: {2}\nПричина: {3}\nID администратора: #{4}.
        /// </summary>
        public static string GEN_BAN_GLOBAL_NTEXT_0 {
            get {
                return ResourceManager.GetString("GEN_BAN_GLOBAL_NTEXT_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0:n0} фишек.
        /// </summary>
        public static string GEN_CHIPS_0 {
            get {
                return ResourceManager.GetString("GEN_CHIPS_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0:n0}.
        /// </summary>
        public static string GEN_CHIPS_1 {
            get {
                return ResourceManager.GetString("GEN_CHIPS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ${0:n0}.
        /// </summary>
        public static string GEN_MONEY_0 {
            get {
                return ResourceManager.GetString("GEN_MONEY_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0:n0}.
        /// </summary>
        public static string GEN_MONEY_1 {
            get {
                return ResourceManager.GetString("GEN_MONEY_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Незнакомка.
        /// </summary>
        public static string NPC_NOTFAM_FEMALE {
            get {
                return ResourceManager.GetString("NPC_NOTFAM_FEMALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Незнакомец.
        /// </summary>
        public static string NPC_NOTFAM_MALE {
            get {
                return ResourceManager.GetString("NPC_NOTFAM_MALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аккаунт с таким логином уже зарегистрирован на проекте!.
        /// </summary>
        public static string NTFC_AUTH_LOGINEXISTS_0 {
            get {
                return ResourceManager.GetString("NTFC_AUTH_LOGINEXISTS_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аккаунт с такой почтой уже зарегистрирован на проекте!.
        /// </summary>
        public static string NTFC_AUTH_MAILEXISTS_0 {
            get {
                return ResourceManager.GetString("NTFC_AUTH_MAILEXISTS_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Письмо с ссылкой для подтверждения регистрации отправлено на {0}.
        /// </summary>
        public static string NTFC_AUTH_REGCONFIRM_SENT_0 {
            get {
                return ResourceManager.GetString("NTFC_AUTH_REGCONFIRM_SENT_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы сможете запросить отправку нового письма с ссылкой для подтверждения регистрации не раньше, чем через {0}!.
        /// </summary>
        public static string NTFC_AUTH_REGCONFIRM_SENT_E_0 {
            get {
                return ResourceManager.GetString("NTFC_AUTH_REGCONFIRM_SENT_E_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы подтвердили Вашу почту и успешно зарегистрировались на проекте! Войдите в свой аккаунт..
        /// </summary>
        public static string NTFC_AUTH_REGCONFIRMED_0 {
            get {
                return ResourceManager.GetString("NTFC_AUTH_REGCONFIRMED_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аккаунт с вашим SocialClubID уже зарегистрирован на проекте!.
        /// </summary>
        public static string NTFC_AUTH_SCIDEXISTS_0 {
            get {
                return ResourceManager.GetString("NTFC_AUTH_SCIDEXISTS_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный логин! Попыток осталось: {0}.
        /// </summary>
        public static string NTFC_AUTH_WRONGLOGIN_0 {
            get {
                return ResourceManager.GetString("NTFC_AUTH_WRONGLOGIN_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный пароль! Попыток осталось: {0}.
        /// </summary>
        public static string NTFC_AUTH_WRONGPASSWORD_0 {
            get {
                return ResourceManager.GetString("NTFC_AUTH_WRONGPASSWORD_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный токен, попробуйте использовать пароль! Попыток осталось: {0}.
        /// </summary>
        public static string NTFC_AUTH_WRONGTOKEN_0 {
            get {
                return ResourceManager.GetString("NTFC_AUTH_WRONGTOKEN_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы должны подождать некоторое время, прежде чем вновь сможете сделать это!.
        /// </summary>
        public static string NTFC_COOLDOWN_GEN_0 {
            get {
                return ResourceManager.GetString("NTFC_COOLDOWN_GEN_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы устали, подождите некоторое время и возвращайтесь!.
        /// </summary>
        public static string NTFC_COOLDOWN_GEN_1 {
            get {
                return ResourceManager.GetString("NTFC_COOLDOWN_GEN_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подождите еще {0}, прежде чем сделать это!.
        /// </summary>
        public static string NTFC_COOLDOWN_GEN_2 {
            get {
                return ResourceManager.GetString("NTFC_COOLDOWN_GEN_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сегодня вы уже делали это, ждите до завтра!.
        /// </summary>
        public static string NTFC_COOLDOWN_GEN_3 {
            get {
                return ResourceManager.GetString("NTFC_COOLDOWN_GEN_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Что-то пошло не так! {0}.
        /// </summary>
        public static string NTFC_GEN_ERROR_0 {
            get {
                return ResourceManager.GetString("NTFC_GEN_ERROR_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Этот человек не является наркозависимым!.
        /// </summary>
        public static string NTFC_OFFER_EMS_DRUGHEAL_0 {
            get {
                return ResourceManager.GetString("NTFC_OFFER_EMS_DRUGHEAL_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Этот человек полностью здоров!.
        /// </summary>
        public static string NTFC_OFFER_EMS_HEAL_0 {
            get {
                return ResourceManager.GetString("NTFC_OFFER_EMS_HEAL_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Этому человеку пока что не требуется помощь психолога!.
        /// </summary>
        public static string NTFC_OFFER_EMS_PSYCHHEAL_0 {
            get {
                return ResourceManager.GetString("NTFC_OFFER_EMS_PSYCHHEAL_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Этот человек сейчас не может принять ваше предложение!.
        /// </summary>
        public static string NTFC_OFFER_ERROR_0 {
            get {
                return ResourceManager.GetString("NTFC_OFFER_ERROR_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация об этом предложении устарела!.
        /// </summary>
        public static string NTFC_OFFER_ERROR_1 {
            get {
                return ResourceManager.GetString("NTFC_OFFER_ERROR_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы успешно реанимировали {0}!.
        /// </summary>
        public static string NTFC_PLAYER_RESURRECT_0 {
            get {
                return ResourceManager.GetString("NTFC_PLAYER_RESURRECT_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} успешно реанимировал Вас!.
        /// </summary>
        public static string NTFC_PLAYER_RESURRECT_1 {
            get {
                return ResourceManager.GetString("NTFC_PLAYER_RESURRECT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не смогли реанимировать {0}!.
        /// </summary>
        public static string NTFC_PLAYER_RESURRECT_2 {
            get {
                return ResourceManager.GetString("NTFC_PLAYER_RESURRECT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} не смог реанимировать Вас!.
        /// </summary>
        public static string NTFC_PLAYER_RESURRECT_3 {
            get {
                return ResourceManager.GetString("NTFC_PLAYER_RESURRECT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} предлагает понести вас.
        /// </summary>
        public static string OFFER_CARRY_TEXT {
            get {
                return ResourceManager.GetString("OFFER_CARRY_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} предлагает вам взять {1}.
        /// </summary>
        public static string OFFER_CASH_TEXT {
            get {
                return ResourceManager.GetString("OFFER_CASH_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} предлагает вам пройти обследование организма.
        /// </summary>
        public static string OFFER_EMS_DIAGNOSTICS_TEXT {
            get {
                return ResourceManager.GetString("OFFER_EMS_DIAGNOSTICS_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} предлагает вам пройти курс лечения наркозависимости, его стоимость: {1}.
        /// </summary>
        public static string OFFER_EMS_DRUGHEAL_TEXT {
            get {
                return ResourceManager.GetString("OFFER_EMS_DRUGHEAL_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} предлагает вам приобрести лечебную таблетку, её стоимость: {1}.
        /// </summary>
        public static string OFFER_EMS_HEAL_TEXT {
            get {
                return ResourceManager.GetString("OFFER_EMS_HEAL_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} предлагает вам оформить медицинскую карту.
        /// </summary>
        public static string OFFER_EMS_MEDCARD_TEXT {
            get {
                return ResourceManager.GetString("OFFER_EMS_MEDCARD_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} предлагает вам пройти психологическую консультацию, её стоимость: {1}.
        /// </summary>
        public static string OFFER_EMS_PSYCHHEAL_TEXT {
            get {
                return ResourceManager.GetString("OFFER_EMS_PSYCHHEAL_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} предлагает вам приобрести медицинскую маску, её стоимость: {1}.
        /// </summary>
        public static string OFFER_EMS_SELLMASK_TEXT {
            get {
                return ResourceManager.GetString("OFFER_EMS_SELLMASK_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} предлагает вам обменяться.
        /// </summary>
        public static string OFFER_EXCHANGE_TEXT {
            get {
                return ResourceManager.GetString("OFFER_EXCHANGE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} предлагает вам взять у него и использовать {1}.
        /// </summary>
        public static string OFFER_GIVE_HEALINGITEM_TEXT {
            get {
                return ResourceManager.GetString("OFFER_GIVE_HEALINGITEM_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} предлагает вам поздороваться.
        /// </summary>
        public static string OFFER_HANDSHAKE_TEXT {
            get {
                return ResourceManager.GetString("OFFER_HANDSHAKE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} предлагает вам сыграть в орел и решку.
        /// </summary>
        public static string OFFER_HEADSORTAILS_TEXT {
            get {
                return ResourceManager.GetString("OFFER_HEADSORTAILS_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} предлагает вам вступить во фракцию {1}.
        /// </summary>
        public static string OFFER_INVITEFRACTION_TEXT {
            get {
                return ResourceManager.GetString("OFFER_INVITEFRACTION_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} предлагает вам вступить в организацию {1}.
        /// </summary>
        public static string OFFER_INVITEORGANISATION_TEXT {
            get {
                return ResourceManager.GetString("OFFER_INVITEORGANISATION_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} выписал вам штраф в размере {1}. Причина: {2}. Будете оплачивать?.
        /// </summary>
        public static string OFFER_POLICE_FINE_TEXT {
            get {
                return ResourceManager.GetString("OFFER_POLICE_FINE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} предлагает вам продажу бизнеса, хотите ознакомиться?.
        /// </summary>
        public static string OFFER_SELL_BUSINESS_TEXT {
            get {
                return ResourceManager.GetString("OFFER_SELL_BUSINESS_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} предлагает вам продажу недвижимости, хотите ознакомиться?.
        /// </summary>
        public static string OFFER_SELL_ESTATE_TEXT {
            get {
                return ResourceManager.GetString("OFFER_SELL_ESTATE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} предлагает вам продажу транспорта, хотите ознакомиться?.
        /// </summary>
        public static string OFFER_SELL_VEHICLE_TEXT {
            get {
                return ResourceManager.GetString("OFFER_SELL_VEHICLE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} предлагает вам подселиться в свой дом.
        /// </summary>
        public static string OFFER_SETTLE_TEXT_0 {
            get {
                return ResourceManager.GetString("OFFER_SETTLE_TEXT_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} предлагает вам подселиться в свою квартиру.
        /// </summary>
        public static string OFFER_SETTLE_TEXT_1 {
            get {
                return ResourceManager.GetString("OFFER_SETTLE_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} предлагает вам посмотреть удостоверение.
        /// </summary>
        public static string OFFER_SHOWFRACTIONDOCS_TEXT {
            get {
                return ResourceManager.GetString("OFFER_SHOWFRACTIONDOCS_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} предлагает вам посмотреть лицензии.
        /// </summary>
        public static string OFFER_SHOWLICENSES_TEXT {
            get {
                return ResourceManager.GetString("OFFER_SHOWLICENSES_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} предлагает вам посмотреть мед. карту.
        /// </summary>
        public static string OFFER_SHOWMEDICALCARD_TEXT {
            get {
                return ResourceManager.GetString("OFFER_SHOWMEDICALCARD_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} предлагает вам посмотреть паспорт.
        /// </summary>
        public static string OFFER_SHOWPASSPORT_TEXT {
            get {
                return ResourceManager.GetString("OFFER_SHOWPASSPORT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} предлагает вам посмотреть трудовую книжку.
        /// </summary>
        public static string OFFER_SHOWRESUME_TEXT {
            get {
                return ResourceManager.GetString("OFFER_SHOWRESUME_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} предлагает вам посмотреть тех. паспорт.
        /// </summary>
        public static string OFFER_SHOWVEHICLEPASSPORT_TEXT {
            get {
                return ResourceManager.GetString("OFFER_SHOWVEHICLEPASSPORT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} предлагает передать вам координаты.
        /// </summary>
        public static string OFFER_WAYPOINTSHARE_TEXT {
            get {
                return ResourceManager.GetString("OFFER_WAYPOINTSHARE_TEXT", resourceCulture);
            }
        }
    }
}
