//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCRPServer.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BCRPServer.Properties.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [BAC] Игрок {0} подозревается в телепорте! Дистанция: {1}.
        /// </summary>
        public static string CHAT_ADMIN_AC_TP_0 {
            get {
                return ResourceManager.GetString("CHAT_ADMIN_AC_TP_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [SKick] {0} выгнал игрока {1} с сервера. Причина: {2}.
        /// </summary>
        public static string CHAT_ADMIN_KICK_SILENT_0 {
            get {
                return ResourceManager.GetString("CHAT_ADMIN_KICK_SILENT_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на снял(а) наручники с {0}.
        /// </summary>
        public static string CHAT_PLAYER_CUFFS_OFF {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_CUFFS_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на надел(а) наручники на {0}.
        /// </summary>
        public static string CHAT_PLAYER_CUFFS_ON {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_CUFFS_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ослабил(а) хватку и отпустил(а) {0}.
        /// </summary>
        public static string CHAT_PLAYER_ESCORT_OFF {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_ESCORT_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на заломал(а) {0} и повел(а) за собой.
        /// </summary>
        public static string CHAT_PLAYER_ESCORT_ON {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_ESCORT_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на показал(а) пальцем на {0}.
        /// </summary>
        public static string CHAT_PLAYER_FP_0 {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_FP_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на показал(а) пальцем на человека.
        /// </summary>
        public static string CHAT_PLAYER_FP_1 {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_FP_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на подбросил(а) монетку.
        /// </summary>
        public static string CHAT_PLAYER_HEADSORTAILS_0 {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_HEADSORTAILS_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На подброшенной монетке выпал орёл..
        /// </summary>
        public static string CHAT_PLAYER_HEADSORTAILS_1 {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_HEADSORTAILS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На подброшенной монетке выпала решка..
        /// </summary>
        public static string CHAT_PLAYER_HEADSORTAILS_2 {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_HEADSORTAILS_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на сорвал(а) маску с {0}.
        /// </summary>
        public static string CHAT_PLAYER_MASKOFF_0 {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_MASKOFF_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на вытащил(а) {0} из {1}.
        /// </summary>
        public static string CHAT_PLAYER_OUTOFVEH_0 {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_OUTOFVEH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на вытащил(а) {0} из багажника {1}.
        /// </summary>
        public static string CHAT_PLAYER_OUTOFVEH_1 {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_OUTOFVEH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на убрал(а) телефон.
        /// </summary>
        public static string CHAT_PLAYER_PHONE_OFF {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_PHONE_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на достал(а) телефон.
        /// </summary>
        public static string CHAT_PLAYER_PHONE_ON {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_PHONE_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на убрал(а) служебный планшет.
        /// </summary>
        public static string CHAT_PLAYER_POLICE_TABLETPC_OFF {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_POLICE_TABLETPC_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на достал(а) служебный планшет.
        /// </summary>
        public static string CHAT_PLAYER_POLICE_TABLETPC_ON {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_POLICE_TABLETPC_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При обыске обнаружен {0}..
        /// </summary>
        public static string CHAT_PLAYER_PSEARCH_CONFISCATE_0 {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_PSEARCH_CONFISCATE_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на конфисковал(а) предмет у {0}.
        /// </summary>
        public static string CHAT_PLAYER_PSEARCH_CONFISCATE_1 {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_PSEARCH_CONFISCATE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При обыске {0} обнаружено {1} документов..
        /// </summary>
        public static string CHAT_PLAYER_PSEARCH_DOCS_FOUND {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_PSEARCH_DOCS_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на взял(а) в руки и просмотрел(а) паспорт {0}.
        /// </summary>
        public static string CHAT_PLAYER_PSEARCH_DOCS_LOOK_0 {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_PSEARCH_DOCS_LOOK_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на взял(а) в руки и просмотрел(а) лицензии {0}.
        /// </summary>
        public static string CHAT_PLAYER_PSEARCH_DOCS_LOOK_1 {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_PSEARCH_DOCS_LOOK_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на взял(а) в руки и просмотрел(а) мед. карту {0}.
        /// </summary>
        public static string CHAT_PLAYER_PSEARCH_DOCS_LOOK_2 {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_PSEARCH_DOCS_LOOK_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на взял(а) в руки и просмотрел(а) удостоверение {0}.
        /// </summary>
        public static string CHAT_PLAYER_PSEARCH_DOCS_LOOK_3 {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_PSEARCH_DOCS_LOOK_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на взял(а) в руки и просмотрел(а) трудовую книжку {0}.
        /// </summary>
        public static string CHAT_PLAYER_PSEARCH_DOCS_LOOK_4 {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_PSEARCH_DOCS_LOOK_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При обыске {0} в карманах обнаружено {1} потенциально нелегальных предметов.
        /// </summary>
        public static string CHAT_PLAYER_PSEARCH_ITEMS_0_FOUND {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_PSEARCH_ITEMS_0_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При обыске {0} в сумке обнаружено {1} потенциально нелегальных предметов.
        /// </summary>
        public static string CHAT_PLAYER_PSEARCH_ITEMS_1_FOUND {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_PSEARCH_ITEMS_1_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При обыске {0} обнаружено {1} потенциально нелегальных предметов.
        /// </summary>
        public static string CHAT_PLAYER_PSEARCH_ITEMS_2_FOUND {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_PSEARCH_ITEMS_2_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При обыске {0} в кобуре обнаружено {1} потенциально нелегальных предметов.
        /// </summary>
        public static string CHAT_PLAYER_PSEARCH_ITEMS_3_FOUND {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_PSEARCH_ITEMS_3_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на надел(а) одноразовые перчатки и приступил(а) к обыску {0}.
        /// </summary>
        public static string CHAT_PLAYER_PSEARCH_START {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_PSEARCH_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на посадил(а) {0} в {1}.
        /// </summary>
        public static string CHAT_PLAYER_PUSHTOVEH_0 {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_PUSHTOVEH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на затолкнул(а) {0} в багажник {1}.
        /// </summary>
        public static string CHAT_PLAYER_PUSHTOVEH_1 {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_PUSHTOVEH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на подобрал(а) {0}.
        /// </summary>
        public static string CHAT_PLAYER_TAKEN {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_TAKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При обыске {0} в багажнике обнаружено {1} потенциально нелегальных предметов.
        /// </summary>
        public static string CHAT_PLAYER_VSEARCH_ITEMS_FOUND_0 {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_VSEARCH_ITEMS_FOUND_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на надел(а) одноразовые перчатки и приступил(а) к обыску {0}.
        /// </summary>
        public static string CHAT_PLAYER_VSEARCH_START {
            get {
                return ResourceManager.GetString("CHAT_PLAYER_VSEARCH_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Через {0} секунд будет произведена очистка предметов, лежащих на земле!.
        /// </summary>
        public static string CHAT_SERVER_WORLD_CLEARITEMS_0 {
            get {
                return ResourceManager.GetString("CHAT_SERVER_WORLD_CLEARITEMS_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Было удалено {0} предметов!.
        /// </summary>
        public static string CHAT_SERVER_WORLD_CLEARITEMS_1 {
            get {
                return ResourceManager.GetString("CHAT_SERVER_WORLD_CLEARITEMS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаление предметов было отменено!.
        /// </summary>
        public static string CHAT_SERVER_WORLD_CLEARITEMS_2 {
            get {
                return ResourceManager.GetString("CHAT_SERVER_WORLD_CLEARITEMS_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на отстегнул(а) ремень безопасности.
        /// </summary>
        public static string CHAT_VEHICLE_BELT_OFF {
            get {
                return ResourceManager.GetString("CHAT_VEHICLE_BELT_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на пристегнул(а) ремень безопасности.
        /// </summary>
        public static string CHAT_VEHICLE_BELT_ON {
            get {
                return ResourceManager.GetString("CHAT_VEHICLE_BELT_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на заблокировал(а) двери.
        /// </summary>
        public static string CHAT_VEHICLE_DOORS_LOCKED {
            get {
                return ResourceManager.GetString("CHAT_VEHICLE_DOORS_LOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на разблокировал(а) двери.
        /// </summary>
        public static string CHAT_VEHICLE_DOORS_UNLOCKED {
            get {
                return ResourceManager.GetString("CHAT_VEHICLE_DOORS_UNLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Двигатель заглох..
        /// </summary>
        public static string CHAT_VEHICLE_ENGINE_BROKEN_0 {
            get {
                return ResourceManager.GetString("CHAT_VEHICLE_ENGINE_BROKEN_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Двигатель не заводится..
        /// </summary>
        public static string CHAT_VEHICLE_ENGINE_BROKEN_1 {
            get {
                return ResourceManager.GetString("CHAT_VEHICLE_ENGINE_BROKEN_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на заглушил(а) двигатель.
        /// </summary>
        public static string CHAT_VEHICLE_ENGINE_OFF {
            get {
                return ResourceManager.GetString("CHAT_VEHICLE_ENGINE_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на запустил(а) двигатель.
        /// </summary>
        public static string CHAT_VEHICLE_ENGINE_ON {
            get {
                return ResourceManager.GetString("CHAT_VEHICLE_ENGINE_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Топливо закончилось..
        /// </summary>
        public static string CHAT_VEHICLE_FUEL_OUTOF {
            get {
                return ResourceManager.GetString("CHAT_VEHICLE_FUEL_OUTOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на закрыл(а) капот.
        /// </summary>
        public static string CHAT_VEHICLE_HOOD_LOCKED {
            get {
                return ResourceManager.GetString("CHAT_VEHICLE_HOOD_LOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на открыл(а) капот.
        /// </summary>
        public static string CHAT_VEHICLE_HOOD_UNLOCKED {
            get {
                return ResourceManager.GetString("CHAT_VEHICLE_HOOD_UNLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на убрал(а) шасси.
        /// </summary>
        public static string CHAT_VEHICLE_LGEAR_OFF {
            get {
                return ResourceManager.GetString("CHAT_VEHICLE_LGEAR_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на выпустил(а) шасси.
        /// </summary>
        public static string CHAT_VEHICLE_LGEAR_ON {
            get {
                return ResourceManager.GetString("CHAT_VEHICLE_LGEAR_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на выключил(а) свет фар.
        /// </summary>
        public static string CHAT_VEHICLE_LIGHTS_OFF {
            get {
                return ResourceManager.GetString("CHAT_VEHICLE_LIGHTS_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на включил(а) свет фар.
        /// </summary>
        public static string CHAT_VEHICLE_LIGHTS_ON {
            get {
                return ResourceManager.GetString("CHAT_VEHICLE_LIGHTS_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на без номерного знака.
        /// </summary>
        public static string CHAT_VEHICLE_NP_NONE {
            get {
                return ResourceManager.GetString("CHAT_VEHICLE_NP_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на вышвырнул(а) {0} из транспорта.
        /// </summary>
        public static string CHAT_VEHICLE_PSGR_KICKED {
            get {
                return ResourceManager.GetString("CHAT_VEHICLE_PSGR_KICKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на закрыл(а) багажник.
        /// </summary>
        public static string CHAT_VEHICLE_TRUNK_LOCKED {
            get {
                return ResourceManager.GetString("CHAT_VEHICLE_TRUNK_LOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на открыл(а) багажник.
        /// </summary>
        public static string CHAT_VEHICLE_TRUNK_UNLOCKED {
            get {
                return ResourceManager.GetString("CHAT_VEHICLE_TRUNK_UNLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IP-адрес.
        /// </summary>
        public static string GEN_BAN_GLOBAL_BTYPES_0 {
            get {
                return ResourceManager.GetString("GEN_BAN_GLOBAL_BTYPES_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Серийный номер.
        /// </summary>
        public static string GEN_BAN_GLOBAL_BTYPES_1 {
            get {
                return ResourceManager.GetString("GEN_BAN_GLOBAL_BTYPES_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Social Club.
        /// </summary>
        public static string GEN_BAN_GLOBAL_BTYPES_2 {
            get {
                return ResourceManager.GetString("GEN_BAN_GLOBAL_BTYPES_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЧС проекта.
        /// </summary>
        public static string GEN_BAN_GLOBAL_BTYPES_3 {
            get {
                return ResourceManager.GetString("GEN_BAN_GLOBAL_BTYPES_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ID блокировки: {0}\nТип: {1}\nДата: {2}\nПричина: {3}\nID администратора: #{4}.
        /// </summary>
        public static string GEN_BAN_GLOBAL_NTEXT_0 {
            get {
                return ResourceManager.GetString("GEN_BAN_GLOBAL_NTEXT_0", resourceCulture);
            }
        }
    }
}
