services:
  db:
    container_name: db
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      ACCEPT_EULA: "Y"
  pma:
    container_name: pma
    image: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_ARBITRARY: 1