namespace BlaineRP.Server.Game.Management.Animations
{
    public enum WalkstyleType
    {
        None = -1,

        Alien,
        Armored,
        Arrogant,
        Brave,
        Casual, Casual2, Casual3, Casual4, Casual5, Casual6,
        Chichi,
        Confident,
        Cop, Cop2, Cop3,
        DefaultMale, DefaultFemale,
        Drunk, Drunk2, Drunk3, Drunk4,
        Femme,
        Fire, Fire2, Fire3,
        Flee,
        Franklin,
        Gangster, Gangster2, Gangster3, Gangster4, Gangster5,
        Grooving,
        Guard,
        Handcuffs,
        Heels, Heels2,
        Hiking,
        Hipster,
        Hobo,
        Hurry,
        Janitor, Janitor2,
        Jog,
        Lemar,
        Lester, Lester2,
        Maneater,
        Michael,
        Money,
        Muscle,
        Posh, Posh2,
        Quick,
        Runner,
        Sad,
        Sassy, Sassy2,
        Scared,
        Sexy,
        Shady,
        Slow,
        Swagger,
        Tough, Tough2,
        Trash, Trash2,
        Trevor,
        Wide,
    }
}