namespace BlaineRP.Client.Game.Input.Enums
{
    internal enum BindTypes
    {
        None = -1,
        Cursor = 0,
        RadarSize,
        ChatInput,
        Inventory,
        FingerPointStart,
        FingerPointStop,
        Crouch,
        Crawl,
        MicrophoneOn,
        MicrophoneOff,
        MicrophoneReload,
        DoorsLock,
        TrunkLook,
        Engine,
        LeftArrow,
        BothArrows,
        RightArrow,
        Lights,
        Belt,
        CruiseControl,
        AutoPilot,
        Interaction,
        Phone,
        Menu,
        HUD,
        TakeItem,
        ReloadWeapon,
        Whistle,
        Animations,
        CancelAnimation,
        Help,
        BlipsMenu,
        AnchorBoat,
        SendCoordsToDriver,
        FlashlightToggle,
        TakeScreenshot,

        ExtraAction0,
        ExtraAction1,

        EnterVehicle,
        PlaneLandingGear,

        weapon0,
        weapon1,
        weapon2,
        pockets0,
        pockets1,
        pockets2,
        pockets3,
        pockets4,
        pockets5,
        pockets6,
        pockets7,
        pockets8,
        pockets9,
        pockets10,
        pockets11,
        pockets12,
        pockets13,
        pockets14,
        pockets15,
        pockets16,
        pockets17,
        pockets18,
        pockets19,
    }
}